### ISSUE TITLE
Panic when creating a MT

### ISSUE THREAD

**Issue by p4u** [vocdoni/arbo#27]
Looks like dvote/db should check for the type before converting the interface but that means arbo is trying to write a transaction of wrong type.

```
panic: interface conversion: db.WriteTx is *prefixeddb.PrefixedWriteTx, not pebbledb.WriteTx

goroutine 486974 [running]:
go.vocdoni.io/dvote/db/pebbledb.WriteTx.Apply({0xc00486f980}, {0x31bebb0, 0xc00c6ca3c0})
        /home/vocdoni/go-dvote/db/pebbledb/pebledb.go:72 +0x54
go.vocdoni.io/dvote/db.(*Batch).Apply(0x80, {0x31bebb0, 0xc00c6ca3c0})
        /home/vocdoni/go-dvote/db/batch.go:61 +0x2b
go.vocdoni.io/dvote/db/prefixeddb.(*PrefixedWriteTx).Apply(0xc011c28ff0, {0x31bebb0, 0xc00c6ca3c0})
        /home/vocdoni/go-dvote/db/prefixeddb/prefixeddb.go:133 +0x2c
github.com/vocdoni/arbo.(*Tree).addBatchInDisk(0xc0144a0770, {0x31bebb0, 0xc00c6ca3c0}, {0xc002023800, 0xc017157218, 0x13276f4}, {0xc002024400, 0x0, 0x734c})
        /home/vocdoni/go/pkg/mod/github.com/vocdoni/arbo@v0.0.0-20211217085703-d56ab859f109/tree.go:315 +0x499
github.com/vocdoni/arbo.(*Tree).AddBatchWithTx(0xc0144a0770, {0x31bebb0, 0xc00c6ca3c0}, {0xc002023800, 0x64, 0x80}, {0xc002024400, 0xc0171572a8, 0xe6e2ad})
        /home/vocdoni/go/pkg/mod/github.com/vocdoni/arbo@v0.0.0-20211217085703-d56ab859f109/tree.go:241 +0x269
go.vocdoni.io/dvote/tree.(*Tree).AddBatch(0xc0133e1488, {0x0, 0x0}, {0xc002023800, 0x64, 0x80}, {0xc002024400, 0x64, 0x80})
        /home/vocdoni/go-dvote/tree/tree.go:132 +0x170
go.vocdoni.io/dvote/censustree.(*Tree).AddBatch(0x20, {0xc002023800, 0xc013fc6580, 0x40}, {0xc002024400, 0x2d18dfe, 0x15})
        /home/vocdoni/go-dvote/censustree/censustree.go:149 +0x146
go.vocdoni.io/dvote/census.(*Manager).Handler(0xc002766460, {0x31abcc8, 0xc005759860}, 0xc01a6d1b80, {0xc01344bd70, 0xc002e99ed8})
        /home/vocdoni/go-dvote/census/handler.go:135 +0x2c46
go.vocdoni.io/dvote/rpcapi.(*RPCAPI).censusLocal(0xc001420360, 0xc01a6d1b80)
        /home/vocdoni/go-dvote/rpcapi/censushandlers.go:15 +0x185
go.vocdoni.io/dvote/rpcapi.(*RPCAPI).route(0xc001420360, {{0x27cc720, 0xc016602af0}, {0xc074e24a43586b0d, 0x6bc042d01d, 0x4575f20}, {0xc00afe1070, 0x1, 0x1}, 0xc00afe1040})
        /home/vocdoni/go-dvote/rpcapi/api.go:109 +0xca
created by go.vocdoni.io/dvote/httprouter.(*HTTProuter).routerHandler.func1
        /home/vocdoni/go-dvote/httprouter/httprouter.go:241 +0x3f9
```

**Comment by p4u** [comment]
So I can reproduce it creating a MT of more than 65k entries (2^16 ? I'm not sure what's the exact number, but around that)

**Comment by p4u** [comment]
Steps to reproduce it.

1. Start a vocdoni-node (you can use master or stage branches)
`go run cmd/dvotenode/dvotenode.go --vochain=stage --logLevel=info --apiAllowPrivate --listenPort=9443 --censusApi --vochainNoWaitSync`

2. Create a census of 70k entries
`go run ./cmd/vochaintest/vochaintest.go --operation=censusGenerate --gwHost http://127.0.0.1:9443/dvote --electionSize=70000`
